#!/bin/bash

echo "🚀 Variables de entorno para Railway:"
echo "====================================="
echo ""
echo "Copia y pega estas variables en Railway Dashboard > Variables:"
echo ""
echo "PORT=4000"
echo "DB_USER=20017932"
echo "DB_PASSWORD=QdmIkw0OvNlJ0Epb"
echo "DB_HOST=cluster0.jpgruo5.mongodb.net"
echo "DB_NAME=verificador-precios-chila"
echo "JWT_SECRET=mi_jwt_secret_super_seguro_123456"
echo "JWT_EXPIRATION_TIME=24h"
echo "JWT_ALGORITHM=HS256"
echo "JWT_ISSUER=verificador-precios-api"
echo "JWT_AUDIENCE=verificador-precios-app"
echo "SENDGRID_API_KEY=SG.ejemplo"
echo "SENDGRID_FROM_EMAIL=noreply@ejemplo.com"
echo "SENDGRID_FROM_NAME=Verificador Precios"
echo "SENDGRID_TEMPLATE_ID_NEW_CLIENT=d-ejemplo123"
echo ""
echo "====================================="
echo "📋 Instrucciones para Railway:"
echo "1. Ve a tu proyecto en Railway"
echo "2. Haz clic en la pestaña 'Variables'"
echo "3. Agrega cada variable una por una"
echo "4. Haz click en 'Deploy' para aplicar los cambios"
